server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://ecoop:ecoop@worktable.coop-e.com/eureka
    healthcheck: true


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: ws-service
          uri: lb://ecoop-query-service
          predicates:
            - Path=/sock-js/**
          filters:
            - PrefixPath=/ecoop-query

        - id: query-service
          uri: lb://ecoop-query-service
          predicates:
            - Path=/queryApi/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ecoop-query

filter:
  authUrl:
    - /queryApi
  zsuserUrl: http://121.43.56.93:8001/

