server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://ecoop:ecoop@e1:9001/eureka/#,http://ecoop:ecoop@e2:9002/eureka/,http://ecoop:ecoop@e3:9003/eureka/
    healthcheck: true


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: ws-service
          uri: lb://ecoop-query-service
          predicates:
          - Path=/sock-js/**
          filters:
          - PrefixPath=/ecoop-query-serivce

        - id: query-service
          uri: lb://ecoop-query-service
          predicates:
            - Path=/queryApi/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ecoop-query

filter:
  authUrl:
    - /queryApi
  zsuserUrl: http://121.43.56.93:8001/

